### PR TITLE
Update changelog.md

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by zoechi** [comment]
Changelog isn't shown at pub.dartlang.org. Should this be fixed in pub or here CHANGELOG.md instead of Changelog.md

**Comment by devoncarew** [comment]
We can change grinder's to `CHANGELOG.md` from `changelog.md`. The all caps is more typical. It would be nice if pub.dartlang.org was case insensitive thought -

**Comment by sethladd** [comment]
this might be a regression. They just moved over to the Dart version of pub.dartlang.org. I'll open an issue over there.

**Comment by sethladd** [comment]
https://github.com/dart-lang/pub-dartlang-dart/issues/17

**Pull request merged**
