### PR TITLE
accept a list of VM args when running the Dart task

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by devoncarew** [comment]
Looks like we're not `unittest` 0.12.0 happy. @sethladd, can you peg the dep at ^0.11.0 in this CL, and we'll clean up our tests in a separate one?

**Comment by sethladd** [comment]
weird. tests passed on my machine.

**Comment by sethladd** [comment]
I just ran my tests via `dart test/all.dart` so maybe it's an issue with grinder and the new test runner.

**Comment by sethladd** [comment]
Look good, please review again. Thanks!

**Comment by devoncarew** [comment]
Lgtm

**Pull request merged**
