### PR TITLE
Mark fail() and GrinderContext.fail() as @alwaysThrows

### PR DESCRIPTION
**Pull request by nex3**
This silences analyzer warnings if these functions are used in a
function that would otherwise require a return value.

### CODE REVIEW

**Comment by nex3** [comment]
It looks like the CI errors are pre-existing.

**Comment by devoncarew** [comment]
I'm going to look at addressing the CI issues in a separate PR.

**Comment by devoncarew** [comment]
If you merge master into this PR the CI should now pass.

**Comment by nex3** [comment]
Done.

**Pull request merged**
