### PR TITLE
readme changes

### PR DESCRIPTION
**Pull request by devoncarew**
Fix https://github.com/google/grinder.dart/issues/169; @seaneagan

### CODE REVIEW

**Comment by seaneagan** [comment]
As in #169 I think we should mention `pub run grinder:grind` for pre-1.10 users, and not mention`pub global run ...` at all, since `pub global activate grinder` / `grind` should be preferred to that.  Also, it currently makes it look like `pub global activate grinder` is a required step, but that's only required if you want to use `grind`.  So "Installing" isn't always necessary... except for that the user needs to add grinder to their `dev_dependencies`, should we mention that?

**Comment by devoncarew** [comment]
Let me call out two different ways of running it - globally activated and locally. I don't think we need to exhaustively list options though, just get people up and running quickly.

**Comment by devoncarew** [comment]
updated -

**Comment by seaneagan** [comment]
Thought it might be easiest to just create another pull request for comparison, see #176.  Also contains some other changes I've been wanting to do.

**Pull request closed without merging**
