### PR TITLE
Dartformat

### PR DESCRIPTION
**Pull request by zoechi**
includes #228

### CODE REVIEW

**Comment by sunglim** [comment]
Just question. Is this automatically formatted?

**Comment by zoechi** [comment]
yup, I have a hard time working without dartformat. I use it all the time. Change a line of code,  press ctrl+e ctrl+f (my custom shortcut for dartformat)

**Comment by zoechi** [comment]
Close this. But would be nice if you could apply dartformat. It makes development much easier when formatting can be done automatically.

**Comment by devoncarew** [comment]
Now that your larger PR has landed, you could do a one-time format of the source and open a new PR :)

**Comment by zoechi** [comment]
Sure, was just waiting for your ok.

**Pull request closed without merging**
