### PR TITLE
add a Dart.runAsync

### PR DESCRIPTION
**Pull request by sethladd**

### CODE REVIEW

**Comment by sethladd** [comment]
cc @devoncarew

**Comment by devoncarew** [comment]
Looks like a line ending issue in a test?

```
00:47 +11: test\grinder_sdk_test.dart: grinder.sdk Dart runAsync
dart.exe C:\Users\appveyor\AppData\Local\Temp\b291689c-0232-11e5-8183-000d3a1108fe\runAsync.dart
hello from runAsync
00:48 +11 -1: test\grinder_sdk_test.dart: grinder.sdk Dart runAsync
  Expected: 'hello from runAsync\n'
    ''
    Actual: 'hello from runAsync\r\n'
    ''
     Which: is different.
  Expected: ...  runAsync\n
    Actual: ...  runAsync\r\n
                          ^
   Differ at offset 20
  
  package:test                       expect
```

**Comment by sethladd** [comment]
Assuming this gets an LGTM, shall I bump the version number, add to CHANGELOG, and publish? I could really use this now :)

**Comment by devoncarew** [comment]
lgtm and sgtm. I think we're due for `0.7.1+2` -

**Pull request merged**
