### PR TITLE
Fix pub global tools.

### PR DESCRIPTION
**Pull request by seaneagan**

### CODE REVIEW

**Comment by devoncarew** [comment]
Thanks! lgtm. Can you add yourself to the https://github.com/google/grinder.dart/blob/master/AUTHORS file as well?

**Comment by devoncarew** [comment]
(added)

**Comment by seaneagan** [comment]
Thanks!  I'll add myself to AUTHORS on the next one.

**Comment by seaneagan** [comment]
oh nevermind,  I see you already did.

**Pull request merged**
