### PR TITLE
add `pub downgrade`.

### PR DESCRIPTION
**Pull request by zoechi**
I want to run my tests twice to check whether the lower bounds of my dependencies are still appropriate.

```dart
_test() {
  Pub.downgrade();
  new PubApp.local('test').run(['-rexpanded']);
  Pub.upgrade();
  new PubApp.local('test').run(['-rexpanded']);
}
```

### CODE REVIEW

**Comment by devoncarew** [comment]
lgtm!

Can you also add yourself to the AUTHORS file?

**Comment by zoechi** [comment]
done

**Comment by devoncarew** [comment]
Thanks! Merging...

**Comment by seaneagan** [comment]
@devoncarew should we be updating the `authors` field in the pubspec as well, so it gets reflected on pub.dartlang.org?

**Comment by zoechi** [comment]
Does it make sense to have two places for that?
I would either leave `pubspec.yaml` as it is and maintain the `AUTHORS` file or remove the authors file completely and maintain only the `pubspec.yaml` file.
A 3rd way is to add a grinder task that updates `AUTHORS` from `pubspec.yaml` ;-)

**Comment by devoncarew** [comment]
They're two separate things. The AUTHORS file is necessary to accept contributions and make sure that the CLA's been signed, and copyright assigned. We can't really mess with the AUTHORS file, it's part of Google's IP process.

I'm not sure the pubspec field is useful for a lot -

**Comment by devoncarew** [comment]
Although this reminds me, we should be updating the changelog :)

**Comment by zoechi** [comment]
done (new PR)

**Comment by seaneagan** [comment]
The pubspec field is what drives the author display in the [pub package page](https://pub.dartlang.org/packages/grinder).  Not super important though since github already [provides](https://github.com/google/grinder.dart/graphs/contributors) an automatically updated view of authors.

**Pull request merged**
