### PR TITLE
Fix process exception in windows

### PR DESCRIPTION
**Pull request by liudonghua123**
try to fix https://github.com/dart-lang/sdk/issues/37751#issuecomment-800369852, https://github.com/dart-lang/sdk/issues/39455.

### CODE REVIEW

**Comment by liudonghua123** [comment]
Could anyone help me with the `grind check-init` error in github ci (https://github.com/google/grinder.dart/runs/2127274421). 😄

**Comment by devoncarew** [comment]
Thanks for the fix! The CI failure doesn't look obvious to me - it looks like an analysis failure you'd see if pub get hadn't been run.

**Comment by liudonghua123** [comment]
> Thanks for the fix! The CI failure doesn't look obvious to me - it looks like an analysis failure you'd see if pub get hadn't been run.

Hi, I checked the logs of ci, `dart pub run` was run in the project directory. But it wasn't run in a generated temp directory before dartanalyzer. And the generated `pubspec.yaml` in temp directory is not complete, the current content is only just one line:

```yaml
name: foo
```

The correct content maybe 

```yaml
name: foo

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  grinder: ^0.8.6
```

So maybe the following code need to update.

https://github.com/google/grinder.dart/blob/eb04f024e7ff42c2b05a82e67d725c13d9f248ee/tool/grind.dart#L22-L34

Maybe like this:

```dart
void checkInit() async {
  final temp = FilePath.createSystemTemp();

  try {
    final pubspec = temp.join('pubspec.yaml').createFile();
    pubspec.writeAsStringSync('''name: foo
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  grinder: ^0.8.6
''', flush: true);
    Dart.run(FilePath.current.join('bin', 'init.dart').path,
        runOptions: RunOptions(workingDirectory: temp.path));
    Process.runSync('pub', ['get']);
    Analyzer.analyze(temp.join('tool', 'grind.dart').path, fatalWarnings: true);
  } finally {
    temp.delete();
  }
}
```

**Review by devoncarew — APPROVED** [review]
Can you merge this against the latest in master (given that your other PR landed)?

**Comment by liudonghua123** [comment]
@devoncarew hi,  I have merged the master branch changes now,  th.

**Comment by devoncarew** [comment]
Thanks again!

**Pull request merged**
