### PR TITLE
Fix #150

### LINKED ISSUE #150: Deprecate TaskFunction
There's a note about it being deprecated in the doc-comments, but it should be marked `@Deprecated(...)` as well.

### PR DESCRIPTION
**Pull request by seaneagan**
@devoncarew

### CODE REVIEW

**Comment by devoncarew** [comment]
Looks like the build system choked here: 

https://travis-ci.org/google/grinder.dart/builds/58621438#L184

because we're now using a deprecated typedef :)

I would either:

- relax our build to allow build infos (tuneup check --ignore-infos)
- in the failed line, instead of doing an `is` check for `TaskFunction`, check against a private typedef with the same sig

**Comment by seaneagan** [comment]
Interesting, works in windows both locally and on appveyor.  `_TaskFunction` is definitely used.  Is this somehow a bug in the analyzer on linux?

**Comment by devoncarew** [comment]
Do not know; this analyzes locally for me as well. I kicked off another copy of the build.

**Comment by seaneagan** [comment]
So locally and on appveyor `pub global activate tuneup` uses analyzer 0.24.4, but on travis it is using 0.24.3.  Presumably it's a bug in analyzer 0.24.3 then.  Maybe the reason travis is using 0.24.3 is related to:

https://code.google.com/p/dart/issues/detail?id=23216#makechanges

**Comment by seaneagan** [comment]
Should we also update grinder's analyzer constraint to ">=0.24.4 <0.25.0"?

**Comment by seaneagan** [comment]
sorry, I mean tuneup's analyzer constraint

**Comment by devoncarew** [comment]
https://github.com/google/tuneup.dart/commit/f9b1f4891a2214604b038482dc82bb5f4e2c030c

:)

**Comment by devoncarew** [comment]
Travis is now pulling an old version of tuneup...

**Comment by devoncarew** [comment]
To make progress, I would either commit as is and hope travis catches up, or change the build to use the `--ignore-infos` flag.

**Comment by seaneagan** [comment]
ok, merging.  We can add `--ignore-infos` if it doesn't get resolved quickly.

**Comment by seaneagan** [comment]
@devoncarew looks like the issue is fixed, can we kick off another travis build on master to fix the build status?  I either don't have access or can't find any "build now" button on the travis site.

**Comment by devoncarew** [comment]
rebuilding now...

**Pull request merged**
